Fix pyenv FAQ env var commands
brettcannon/python-launcher pull request #144
Opened 2021-08-19 14:47 UTC by cas--

When using pyenv and global not set (defaulting to system) or global set to `system` the Launcher was unable to determine correct version to use.

Fixed by using `pyenv exec` to correctly determine current Python version instead of parsing pyenv config files.

Fixes #141

2021-08-23 19:21 UTC, brettcannon requested changes
One tricky thing with this compared to the old solution is `PY_PYTHON` is the default version to use when no specific major version is requested, e.g. it's not the same as `PY_PYTHON2`. That means this isn't technically right as you have to make an assumption as to what major version of Python people want to depend on compared to the solution of reading `(pyenv root)/version`).

Maybe it's better to list both solutions?

2021-08-23 19:21 UTC, brettcannon commented on README.md
> +export PY_PYTHON3=$(pyenv exec python3 -c "import sys; print(*sys.version_info[0:2], sep='.')")
```suggestion
export PY_PYTHON=$(pyenv exec python3 -c "import sys; print(*sys.version_info[0:2], sep='.')")
```

2021-08-23 19:21 UTC, brettcannon commented on README.md
> +set -gx PY_PYTHON3 (pyenv exec python3 -c "import sys; print(*sys.version_info[0:2], sep='.')")
```suggestion
set -gx PY_PYTHON (pyenv exec python3 -c "import sys; print(*sys.version_info[0:2], sep='.')")
```

2021-08-29 14:31 UTC, cas-- commented
I merged your suggestions but then changed my mind and reverted as I think there has been a misunderstanding.

> One tricky thing with this compared to the old solution is PY_PYTHON is the default version to use when no specific major version is requested e.g. it's not the same as PY_PYTHON2

The use of `python` is not meant to refer to `python2`. Using `$(pyenv exec python)` solution mirrors the old solution since pyenv `python` is what the user set via pyenv global (the `(pyenv root)/version` file) or fallback to system. 

I hope this make sense?

2021-08-30 20:00 UTC, brettcannon commented
Then please drop the `PY_PYTHON3` example as I don't think many people will care enough to warrant making the example more complex.

2021-08-30 20:01 UTC, brettcannon requested changes

2021-08-30 20:01 UTC, brettcannon commented on README.md
> +export PY_PYTHON=$(pyenv exec python -c "import sys; print('.'.join(map(str, sys.version_info[0:2])))")
```suggestion
export PY_PYTHON=$(pyenv exec python -c "import sys; print('.'.join(map(str, sys.version_info[:2])))")
```

2021-08-30 20:01 UTC, brettcannon commented on README.md
> +export PY_PYTHON3=$(pyenv exec python3 -c "import sys; print(*sys.version_info[0:2], sep='.')")
```suggestion
```

2021-08-30 20:01 UTC, brettcannon commented on README.md
> +set -gx PY_PYTHON3 (pyenv exec python3 -c "import sys; print(*sys.version_info[0:2], sep='.')")
```suggestion
```

2021-08-30 20:01 UTC, brettcannon commented on README.md
> +set -gx PY_PYTHON (pyenv exec python -c "import sys; print('.'.join(map(str, sys.version_info[0:2])))")
```suggestion
set -gx PY_PYTHON (pyenv exec python -c "import sys; print('.'.join(map(str, sys.version_info[:2])))")
```

2021-09-01 10:55 UTC, cas-- commented
I agree, was including it for completeness for `-3` option

2021-09-10 22:11 UTC, brettcannon requested changes

2021-09-10 22:11 UTC, brettcannon commented on README.md
> +versions, you'll want to set the version the Launcher to the pyenv
```suggestion
versions, you'll want to set the version the Launcher uses to the pyenv 
```

2021-09-10 22:11 UTC, brettcannon commented on README.md
> +Add these lines to your `.zshrc` or `.bashrc` file:
```suggestion
Add this line to your `.zshrc` or `.bashrc` file:
```

2021-09-10 22:11 UTC, brettcannon commented on README.md
> +Or these lines to your `~/.config/fish/config.fish` file:
```suggestion
Or this line to your `~/.config/fish/config.fish` file:
```

2021-09-10 22:11 UTC, brettcannon approved these changes

2021-09-10 22:13 UTC, brettcannon requested changes
I just realized the changes were made against the main copy of the README and not the template which the README is generated from. Would you mind applying the changes to https://github.com/brettcannon/python-launcher/blob/main/docs/readme/template.md instead?

2021-09-10 22:33 UTC, merged

2021-09-10 22:33 UTC, brettcannon commented
Thanks for the help with this!